# fly.toml app configuration file generated for flash-card-app-nodejs on 2024-07-01T14:43:13+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flash-card-app-nodejs'
primary_region = 'arn'

[build]

[env]
  HOST = '0.0.0.0'
  NODE_ENV = 'production'
  PORT = '5068'

[http_service]
  internal_port = 5068
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
